import numpy as np
from numpy import exp, sqrt

# Absorption
# this functions is based on
# Ainslie M. A., McColm J. G., "A simplified formula for viscous and 
# chemical absorption in sea water", Journal of the Acoustical Society of 
# America, 103(3), 1671-1672, 1998.
# Semme J. Dijkstra November 11, 2019

def absorption( t,d,s,pH,f):
    # t: temp in C
    # d: Depth in m
    # s: Salinity in PSU
    # pH: acidity 
    # f: Central Frequency in Hz - this may be an array

    # Bring the depth to kms
    d=d/1000

    # Bring the frequency to kHz
    f=f/1000

    ## Viscous absorption generated by particle motion
    a=null

    ## Absorption by specific chemicals

    # Boric acid Relaxation frequency
    f1=null

    # Magnesium sulfate relaxation frequency
    f2=null

    # Add the chemical absorption to the physical absorption

    a=null

    return a