import numpy as np
from numpy import exp, sqrt

# Absorption
# this functions is based on
# Ainslie M. A., McColm J. G., "A simplified formula for viscous and 
# chemical absorption in sea water", Journal of the Acoustical Society of 
# America, 103(3), 1671-1672, 1998.
# Semme J. Dijkstra November 11, 2019

def absorption( t,d,s,pH,f):
    # t: temp in C
    # d: Depth in m
    # s: Salinity in PSU
    # pH: acidity 
    # f: Central Frequency in Hz - this may be an array

    # Bring the depth to kms
    d=d/1000

    # Bring the frequency to kHz
    f=f/1000

    ## Viscous absorption generated by particle motion
    a=0.00049*f**2*exp(-(t/27+d/17))

    ## Absorption by specific chemicals

    # Boric acid Relaxation frequency
    f1=0.78*sqrt(s/35)*exp(t/26)

    # Magnesium sulfate relaxation frequency
    f2=42*exp(t/17)

    # Add the chemical absorption to the physical absorption

    a=a+0.106*f1*f**2/(f1**2+f**2)*exp((pH-8)/.56)+ .52*(1+t/43)*s/35*f2*f**2/(f2**2+f**2)*exp(-d/6);

    return a

